# Generated by Django 3.1.6 on 2021-02-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='videos',
            new_name='number_videos',
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.category'),
        ),
        migrations.AlterField(
            model_name='class',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='class',
            name='sku',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
