# Generated by Django 3.1.7 on 2021-03-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('category', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], max_length=254, null=True)),
                ('description', models.TextField()),
                ('number_lectures', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('instructor', models.CharField(max_length=254)),
                ('tags', models.ManyToManyField(to='items.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('instructor', models.CharField(max_length=254)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.program')),
            ],
        ),
    ]
