# Generated by Django 3.1.6 on 2021-03-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('category_name', models.CharField(max_length=254)),
                ('category_friendly_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('number_classes', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('instructor', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('instructor', models.CharField(max_length=254)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.program')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
