# Generated by Django 3.1.7 on 2021-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-id']},
        ),
    ]
