# Generated by Django 3.1.6 on 2021-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210305_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Beginners', 'Beginners'), ('Challenges', 'Challenges'), ('Dynamic', 'Dynamic'), ('Therapeutic', 'Therapeutic')], max_length=254),
        ),
    ]
