# Generated by Django 3.1.7 on 2021-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210317_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='price',
        ),
    ]
