# Generated by Django 3.1.6 on 2021-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210309_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Beginners', 'Beginners'), ('Challenges', 'Challenges'), ('Dynamic', 'Dynamic'), ('Therapeutic', 'Therapeutic')], max_length=254, null=True),
        ),
    ]
