# Generated by Django 3.1.6 on 2021-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210309_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(to='items.Tag'),
        ),
    ]
