# Generated by Django 3.1.6 on 2021-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_program_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], max_length=254, null=True),
        ),
    ]
