# Generated by Django 3.1.6 on 2021-03-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210309_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Lecture',
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='number_classes',
            new_name='number_lectures',
        ),
    ]
